#!/usr/bin/env bash

crear_grupo() {
	echo -n "Introduce el nombre del nuevo grupo"
	read -r grupo
	groupadd "$grupo"
}

validar_contrasenia(){
	while true; do
		read -r -s -p "Ingresa tu contraseña: " contrasenia
		echo
		if test "$(echo "$contrasenia" | grep "[0-9]")" && \
   		test "$(echo "$contrasenia" | grep "[a-z]")" && test "$(echo "$contrasenia" | grep "[A-Z]")" && \
   		test "$(echo "$contrasenia" | grep "[-_?\!@#\$%\^\&+=]")" && test "$(echo "$contrasenia" | grep -E '^.{9,}$')"; then
	    	echo "Contraseña válida."
	    	break
		else
	    	echo "Error: La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial."
		fi
	done
}
crear_cuotas(){
	local login_usuario="$1"
	quotaon -v /home
	while true; do
		echo "¿Desea que el usuario creado tenga cuotas?"
		echo "1) Sí"
		echo "2) No"
		read -r cuota
		case "$cuota" in
		1) 
			echo -n "Introduce el límite suave en MB: "
			read -r limite_suave
			echo -n "Introduce el límite duro en MB: "
			read -r limite_duro
			setquota -u "$login_usuario" "$limite_suave"M "$limite_duro"M 0 0 /home
			if test $? -eq 0; then
				echo "Cuota asignada correctamente"
				break
			else 
				echo "Error al asignar la cuota"
				break
			fi 
			;;
		2) 
			break
			;;
		*)
			echo "Opción no válida"
			;;
		esac
	done
}


agregar_sudo(){
	local usuario="$1"
	while true; do
		echo "¿Desea que el usario pueda ejecutar comandos como sudo?"
		echo "1)Sí"
		echo "2)No"
		read -r opcion_sudo
		case "$opcion_sudo" in
			1)
				while true; do
					echo "Elija qué comandos va a ejecutar el usuario como sudo"
					echo "1)Todos los comandos "
					echo "2)Especificar comandos "
					echo "3)Regresar al menú anterior "
					read -r comandos_sudo
					case "$comandos_sudo" in
						1)
							usermod -aG sudo "$usuario"
							echo "El usuario puede ejecutar todos los comandos como sudo"
							return
							;;
						2)
							echo "Introduzca los comandos que podrá ejecutar el usuario, separados por coma, separado por espacios y con la ruta completa"
							echo "Ejemplo:/usr/bin/passwd, /usr/bin/ip"
							read -r comandos_sudo
							echo "$usuario ALL=(ALL) $comandos_sudo" | sudo tee /etc/sudoers.d/"$usuario" > /dev/null
							if sudo visudo -c -f /etc/sudoers.d/"$usuario"; then
							     sudo chmod 440 /etc/sudoers.d/"$usuario"
							     echo "Se han configurado los comandos permitidos para el usuario."
							     return
							else
							     echo "Error en la configuración. No se aplicaron cambios."
							     sudo rm -f /etc/sudoers.d/"$usuario"
							fi
							return
							;;
						3)
							break
							;;
						*)
							echo "Opción no válida"
							;;
					esac
				done
					
				;;
			2)
				break
				;;
			*)
				echo "Opción no válida"
				;;
		esac
	done
	
}

crear_usuario() {
	echo -n "Introduce el login que se usará para el nuevo usuario: "
	read -r login
	echo -n "Introduce el grupo al que va a pertenecer el usuario: "
	read -r grupo
	if ! grep -q "^$grupo:" /etc/group; then
	    echo "Error, el grupo ingresado no existe, primero debes crearlo"
	    return 1
	fi
	echo -n "Introduce un comentario para describir al nuevo usuario: "
	read -r comentario
	echo -n "Introduce el nombre del directorio hogar del nuevo usuario: "
	read -r directorio_home
	echo -n "Introduce el shell del nuevo usuario: "
	read -r tipo_shell
	validar_contrasenia
	useradd -c "$comentario" -d /home/"$directorio_home" -m -k /etc/skel -g "$grupo" -s /bin/"$tipo_shell" "$login"
	echo "$login":"$contrasenia" | chpasswd;
	crear_cuotas "$login"
	agregar_sudo "$login"
	
}

while true; do
	echo "---Programa para crear usuario---"
	echo "Selecciona una opción"
	echo "1) Crear un nuevo usuario"
	echo "2) Crear un nuevo grupo"
	echo "3) Salir"
	read -r opcion
	case "$opcion" in
		1)
			crear_usuario
			;;
		2)
			crear_grupo
			;;
		3)
			exit 0
			;;
		*)
			echo "Opción no válida"
			;;
	esac
done
